version: '3.9'
networks:
  test-verification:
services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - 8080:80
    depends_on:
      - app
      - mysql
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - test-verification

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: app
    volumes:
      - ./:/var/www/html
    networks:
      - test-verification

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - test-verification